# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(655, 344)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.find_device = QtWidgets.QPushButton(self.centralwidget)
        self.find_device.setGeometry(QtCore.QRect(10, 10, 300, 120))
        self.find_device.setObjectName("find_device")
        self.twrp_start = QtWidgets.QPushButton(self.centralwidget)
        self.twrp_start.setGeometry(QtCore.QRect(10, 140, 300, 120))
        self.twrp_start.setObjectName("twrp_start")
        self.list_devices = QtWidgets.QListWidget(self.centralwidget)
        self.list_devices.setGeometry(QtCore.QRect(330, 10, 310, 250))
        self.list_devices.setObjectName("list_devices")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.find_device.setText(_translate("MainWindow", "Find device"))
        self.twrp_start.setText(_translate("MainWindow", "TWRP"))
